version: 2

# 🛡️ Enterprise Security-First Dependency Management
# Follows n, n-1, n-2 version policy with automated security updates

updates:
  # ===== ROOT WORKSPACE =====
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "🔒 security"
      prefix-development: "⬆️ deps"
      include: "scope"
    reviewers:
      - "security-team"
    assignees:
      - "security-lead"
    labels:
      - "dependencies"
      - "security"
      - "automated"
    # Security-focused update strategy
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
    ignore:
      # Prevent automatic major version updates (manual review required)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
  # ===== BACKEND SECURITY =====
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 8
    target-branch: "develop"
    commit-message:
      prefix: "🔒 backend-security"
      prefix-development: "⬆️ backend-deps"
      include: "scope"
    reviewers:
      - "backend-team"
      - "security-team"
    assignees:
      - "backend-lead"
    labels:
      - "backend"
      - "dependencies"
      - "security"
      - "automated"
    # Prioritize security updates for backend
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
    # Critical security packages - allow immediate updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Exceptions for critical security packages
      - dependency-name: "express"
        update-types: []  # Allow all updates for Express
      - dependency-name: "helmet"
        update-types: []  # Allow all updates for Helmet
      - dependency-name: "cors"
        update-types: []  # Allow all updates for CORS
      - dependency-name: "jsonwebtoken"
        update-types: []  # Allow all updates for JWT
      - dependency-name: "bcryptjs"
        update-types: []  # Allow all updates for bcrypt
      - dependency-name: "validator"
        update-types: []  # Allow all updates for validator

  # ===== FRONTEND SECURITY =====
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "🔒 frontend-security"
      prefix-development: "⬆️ frontend-deps"
      include: "scope"
    reviewers:
      - "frontend-team"
      - "security-team"
    assignees:
      - "frontend-lead"
    labels:
      - "frontend"
      - "dependencies"
      - "security"
      - "automated"
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Allow all updates for critical frontend security packages
      - dependency-name: "next"
        update-types: []  # Allow all updates for Next.js
      - dependency-name: "react"
        update-types: []  # Allow all updates for React
      - dependency-name: "react-dom"
        update-types: []  # Allow all updates for React DOM

  # ===== AUTHENTICATION SERVICE =====
  - package-ecosystem: "npm"
    directory: "/auth"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "develop"
    commit-message:
      prefix: "🔐 auth-security"
      prefix-development: "⬆️ auth-deps"
      include: "scope"
    reviewers:
      - "security-team"
      - "auth-team"
    assignees:
      - "security-lead"
    labels:
      - "auth"
      - "dependencies"
      - "security"
      - "critical"
      - "automated"
    # Most aggressive update policy for auth service
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      # Allow major updates for critical auth packages
      - dependency-name: "jsonwebtoken"
        update-type: "version-update:semver-major"
      - dependency-name: "bcryptjs"
        update-type: "version-update:semver-major"
      - dependency-name: "passport"
        update-type: "version-update:semver-major"
    ignore: []  # Don't ignore any updates for auth service

  # ===== DOCKER SECURITY =====
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    target-branch: "develop"
    commit-message:
      prefix: "🐳 docker-security"
      include: "scope"
    reviewers:
      - "devops-team"
      - "security-team"
    assignees:
      - "devops-lead"
    labels:
      - "docker"
      - "infrastructure"
      - "security"
      - "automated"

  # ===== GITHUB ACTIONS SECURITY =====
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "11:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "🔧 actions-security"
      include: "scope"
    reviewers:
      - "devops-team"
      - "security-team"
    assignees:
      - "devops-lead"
    labels:
      - "github-actions"
      - "ci-cd"
      - "security"
      - "automated"

# 🚨 Security Configuration Notes:
#
# 1. VERSION POLICY: Follows n, n-1, n-2 strategy
#    - Security updates: Always allowed (immediate)
#    - Patch updates: Allowed (weekly review)
#    - Minor updates: Allowed (weekly review)
#    - Major updates: Manual review required (except critical security packages)
#
# 2. UPDATE FREQUENCY:
#    - Auth service: Daily (highest security priority)
#    - Backend: Daily (high security impact)
#    - Frontend: Weekly (lower security impact)
#    - Root workspace: Weekly (coordination updates)
#    - Docker: Weekly (infrastructure stability)
#    - GitHub Actions: Weekly (CI/CD stability)
#
# 3. REVIEW REQUIREMENTS:
#    - All updates require security team review
#    - Critical packages have dedicated assignees
#    - Automated testing must pass before merge
#
# 4. CRITICAL SECURITY PACKAGES (immediate updates allowed):
#    - Authentication: jsonwebtoken, bcryptjs, passport
#    - Web security: helmet, cors, express
#    - Input validation: validator, joi
#    - Frontend frameworks: react, next.js
#
# 5. BRANCH STRATEGY:
#    - All updates target 'develop' branch
#    - Security patches can be fast-tracked to 'main'
#    - Major updates require manual testing
#
# 6. MONITORING:
#    - Security team notified of all updates
#    - Failed updates trigger immediate review
#    - Metrics tracked for dependency health