# Repository settings for prompt-card-system
# This file can be used with the Settings GitHub App or similar automation

repository:
  name: prompt-card-system
  description: "A comprehensive prompt card management system with intelligent categorization and testing capabilities"
  homepage: ""
  topics: ["prompt", "ai", "management", "testing", "cards", "nodejs", "react", "typescript"]
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_pages: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection settings
branches:
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI/CD Pipeline"
          - "Security Scan"
          - "PR Quality / Template Completion"
          - "PR Quality / Issue Linking"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        restrict_pushes: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI/CD Pipeline"
          - "Security Scan"
          - "Tests"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        restrict_pushes: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Issue and PR templates
issue_template_chooser:
  enabled: true

# Collaborators and team access
# Note: These would be configured based on actual team structure
teams:
  - name: maintainers
    permission: admin
  - name: contributors
    permission: write

# Labels are managed by the labels-sync.yml workflow

# Security
security:
  secret_scanning: true
  secret_scanning_push_protection: true
  dependency_graph: true
  automated_security_fixes: true
  vulnerability_alerts: true

# Merge settings
merge_settings:
  squash_title_template: "{{title}} (#{{number}})"
  squash_body_template: |
    {{body}}
    
    Co-authored-by: {{authors}}
  merge_title_template: "Merge pull request #{{number}} from {{head_ref}}"
  merge_body_template: |
    {{title}}
    
    {{body}}

# Actions permissions
actions:
  permissions:
    contents: read
    issues: write
    pull-requests: write
    checks: write
    actions: read
    security-events: write
    statuses: write
    deployments: write

# Environments (for deployment)
environments:
  - name: development
    protection_rules: []
    deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      custom_branches: ["develop"]
  
  - name: staging
    protection_rules:
      - type: required_reviewers
        reviewers: ["tbowman01"]
    deployment_branch_policy:
      protected_branches: true
  
  - name: production
    protection_rules:
      - type: required_reviewers
        reviewers: ["tbowman01"]
      - type: wait_timer
        minutes: 5
    deployment_branch_policy:
      protected_branches: true