name: 🐛 Bug Report
description: Create a report to help us improve the system
title: "[BUG]: "
labels: ["type:bug", "status:triage", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! The more details you provide, the faster we can resolve the issue.
        
  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported
          required: true
        - label: I have reproduced the issue with the latest version
          required: true
        - label: I have provided all the information requested in this template
          required: true
          
  - type: dropdown
    attributes:
      label: Priority Level
      description: How critical is this bug to your workflow?
      options:
        - Medium (default)
        - Low - Nice to fix but not urgent
        - High - Blocking my work
        - Critical - System is unusable
      default: 0
      
  - type: dropdown
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Frontend (React/Next.js)
        - Backend (Node.js/Express)
        - Database (SQLite)
        - API Endpoints
        - Authentication
        - Testing Framework
        - Monitoring/Analytics
        - Docker/Infrastructure
        - Documentation
        - Other (specify in description)
      multiple: true
      
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered...
      value: "**What happened?**\n\n**What did you expect to happen?**\n\n"
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened (include any error messages)
      placeholder: What actually happened? Include any error messages, stack traces, or screenshots.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      value: |
        **Operating System:** (e.g., Windows 10, macOS 12.0, Ubuntu 20.04)
        **Browser:** (if applicable - Chrome 100, Firefox 98, Safari 15)
        **Node.js Version:** (run `node --version`)
        **NPM Version:** (run `npm --version`)
        **Docker Version:** (if using Docker - run `docker --version`)
        **Other relevant versions:**
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or paste relevant log outputs
      placeholder: |
        Screenshots help us understand the visual issues.
        Logs help us understand technical issues.
        
        Paste logs between triple backticks:
        ```
        log output here
        ```
        
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Does this happen consistently or intermittently?
        - Have you found any workarounds?
        - When did you first notice this issue?
        - Are there any related issues?
        
  - type: checkboxes
    attributes:
      label: Impact Assessment
      description: Help us understand the impact of this bug
      options:
        - label: This blocks core functionality
        - label: This affects user experience
        - label: This causes data loss or corruption  
        - label: This is a security concern
        - label: This affects system performance
        - label: This only affects edge cases
        - label: This has a workaround available