blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/tbowman01/prompt-card-system/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 📚 Documentation
    url: https://github.com/tbowman01/prompt-card-system/docs
    about: Check our comprehensive documentation for setup, usage, and API reference
  - name: 🚀 Development Chat
    url: https://github.com/tbowman01/prompt-card-system/discussions/categories/development
    about: Technical discussions about contributing to the project
  - name: 🆘 Get Help
    url: https://github.com/tbowman01/prompt-card-system/discussions/categories/q-a
    about: Get help with installation, configuration, or usage questions