name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["type:feature", "status:triage", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make this project better for everyone.
        
  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
        - label: I have provided all the information requested in this template
          required: true
          
  - type: dropdown
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New functionality
        - Enhancement to existing feature
        - UI/UX improvement
        - Performance optimization
        - Developer experience improvement
        - Integration with external service
        - Security enhancement
        - Documentation improvement
        - Testing improvement
      default: 0
      
  - type: dropdown
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Medium (default)
        - Low - Nice to have
        - High - Important for my workflow  
        - Critical - Essential for my use case
      default: 0
      
  - type: dropdown
    attributes:
      label: Component
      description: Which part of the system would this feature affect?
      options:
        - Frontend (React/Next.js)
        - Backend (Node.js/Express)
        - Database (SQLite)
        - API Design
        - Authentication/Authorization
        - Testing Framework
        - Monitoring/Analytics
        - Docker/Infrastructure
        - Documentation
        - CI/CD Pipeline
        - Other (specify in description)
      multiple: true
      
  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Describe the problem or limitation you're facing...
        
        - What is currently difficult or impossible to do?
        - What workflows are inefficient?
        - What functionality is missing?
      value: |
        **Current Situation:**
        
        **Pain Points:**
        
        **Impact:**
        
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: |
        What would you like to see implemented?
        
        Be as specific as possible about:
        - What the feature should do
        - How users would interact with it
        - What the expected behavior is
      value: |
        **Proposed Feature:**
        
        **User Interaction:**
        
        **Expected Behavior:**
        
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: User Stories
      description: Describe how different types of users would benefit from this feature
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example:
        As a developer, I want to automatically validate prompt cards so that I can ensure quality without manual testing.
      value: |
        **Primary User Story:**
        As a [user type], I want [feature] so that [benefit].
        
        **Additional User Stories:**
        - As a [user type], I want [feature] so that [benefit].
        - As a [user type], I want [feature] so that [benefit].
        
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete and successful?
      placeholder: |
        Define the specific requirements that must be met:
        
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
      value: |
        **Must Have:**
        - [ ] 
        - [ ] 
        - [ ] 
        
        **Should Have:**
        - [ ] 
        - [ ] 
        
        **Could Have:**
        - [ ] 
        - [ ] 
        
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        - What alternatives have you considered?
        - Are there existing tools or features that partially solve this?
        - What are the pros/cons of different approaches?
        
  - type: dropdown
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - I'm not sure
        - Simple - A few hours of work
        - Moderate - A few days of work
        - Complex - A few weeks of work
        - Very Complex - Multiple sprints
      default: 0
      
  - type: textarea
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or implementation notes
      placeholder: |
        - Any specific technical requirements?
        - Integration points with existing systems?
        - Performance considerations?
        - Security implications?
        - Database schema changes needed?
        
  - type: textarea
    attributes:
      label: Mockups or Examples
      description: Visual examples, mockups, wireframes, or references
      placeholder: |
        - Screenshots of similar features in other tools
        - Wireframes or mockups
        - Code examples
        - Links to reference implementations
        
        You can drag and drop images here or paste links.
        
  - type: checkboxes
    attributes:
      label: Impact Assessment
      description: Help us understand the potential impact of this feature
      options:
        - label: This would improve user experience significantly
        - label: This would save time for users
        - label: This would enable new use cases
        - label: This would improve system performance
        - label: This would enhance security
        - label: This would reduce maintenance burden
        - label: This would help with scalability
        - label: This would improve developer productivity
        
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Similar features in other tools you've used
        - References to standards or best practices
        - Community feedback or requests you've seen
        - Timeline considerations or deadlines