name: 🛡️ Security Issue
description: Report a security vulnerability (use private channels for critical issues)
title: "[SECURITY]: "
labels: ["type:security", "priority:high", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT SECURITY NOTICE ⚠️
        
        **For Critical Security Issues:**
        Please DO NOT create a public issue. Instead:
        - Email: [security@your-domain.com] (replace with actual email)
        - Use GitHub's private vulnerability reporting
        - Contact maintainers directly
        
        **Use this public template only for:**
        - General security improvements
        - Non-sensitive security questions
        - Security feature requests
        - Documentation improvements
        
  - type: checkboxes
    attributes:
      label: Security Checklist
      description: Please confirm you understand the security reporting process
      options:
        - label: This is NOT a critical vulnerability that could be exploited
          required: true
        - label: I have considered reporting this privately first
          required: true
        - label: I understand this issue will be publicly visible
          required: true
          
  - type: dropdown
    attributes:
      label: Security Issue Type
      description: What type of security issue are you reporting?
      options:
        - General security improvement
        - Security feature request
        - Security documentation issue
        - Security testing improvement
        - Compliance or best practice issue
        - Configuration security issue
        - Dependency security update
        - Low-risk vulnerability
      default: 0
      
  - type: dropdown
    attributes:
      label: Severity Level
      description: How would you rate the severity of this issue?
      options:
        - Low - Minimal impact, requires specific conditions
        - Medium - Moderate impact with some prerequisites
        - High - Significant impact but not immediately exploitable
        - Critical - Immediate threat (should be reported privately!)
      default: 0
      
  - type: dropdown
    attributes:
      label: Component
      description: Which component is affected by this security issue?
      options:
        - Authentication system
        - Authorization/permissions
        - API endpoints
        - Database security
        - Frontend security (XSS, etc.)
        - Input validation
        - Data encryption
        - Session management
        - Docker configuration
        - CI/CD pipeline
        - Dependencies
        - Configuration files
        - Logging/monitoring
        - Other (specify in description)
      multiple: true
      
  - type: textarea
    attributes:
      label: Security Issue Description
      description: Describe the security issue or improvement needed
      placeholder: |
        Provide a clear description of:
        - What security aspect is affected
        - What could potentially happen
        - Why this is a concern
        
        **Do NOT include:**
        - Exploit code for critical vulnerabilities
        - Step-by-step exploitation instructions
        - Sensitive system information
      value: |
        **Issue Summary:**
        
        **Security Concern:**
        
        **Potential Impact:**
        
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Current Behavior
      description: How does the system currently handle this security aspect?
      placeholder: |
        Describe the current security implementation or lack thereof.
        What security measures are currently in place?
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Recommended Improvement
      description: What security improvement do you suggest?
      placeholder: |
        Suggest specific improvements:
        - Security controls to implement
        - Best practices to follow
        - Configuration changes needed
        - Dependencies to update
      value: |
        **Recommended Solution:**
        
        **Security Controls:**
        
        **Best Practices:**
        
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to Verify
      description: How can the security improvement be verified? (No exploit details!)
      placeholder: |
        Describe how to verify the security issue exists and how to test the fix:
        - General testing approach
        - Security tools that could be used
        - Verification steps
        
        **Do NOT include actual exploitation steps!**
        
  - type: dropdown
    attributes:
      label: Standards Compliance
      description: Which security standards or frameworks does this relate to?
      options:
        - OWASP Top 10
        - NIST Cybersecurity Framework
        - CWE (Common Weakness Enumeration)
        - GDPR/Privacy regulations
        - SOC 2 compliance
        - ISO 27001
        - PCI DSS
        - Company security policies
        - Industry best practices
        - Not applicable
      multiple: true
      
  - type: textarea
    attributes:
      label: Security References
      description: Any relevant security documentation, standards, or resources
      placeholder: |
        - OWASP documentation links
        - CWE numbers
        - Security advisories
        - Best practice guides
        - Relevant CVE numbers (for dependency issues)
        
  - type: checkboxes
    attributes:
      label: Impact Assessment
      description: What could be impacted by this security issue?
      options:
        - label: User data confidentiality
        - label: Data integrity
        - label: System availability
        - label: Authentication bypass
        - label: Authorization bypass
        - label: Information disclosure
        - label: Code execution
        - label: Privilege escalation
        - label: Denial of service
        - label: Privacy violations
        
  - type: textarea
    attributes:
      label: Affected Versions
      description: Which versions are affected by this security issue?
      placeholder: |
        - Version range affected
        - When was this issue introduced?
        - Are there any versions that are not affected?
        
  - type: textarea
    attributes:
      label: Additional Context
      description: Any additional context about this security issue
      placeholder: |
        - How did you discover this issue?
        - Are you aware of any public discussion about this?
        - Any workarounds available?
        - Timeline considerations?
        
  - type: markdown
    attributes:
      value: |
        ## 🔒 Next Steps
        
        After you submit this issue:
        1. The security team will review within 48 hours
        2. You'll receive an initial response with next steps
        3. If this needs private handling, we'll contact you directly
        4. We'll work together on a fix and disclosure timeline
        
        Thank you for helping keep the project secure!