groups:
  - name: prompt_card_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} requests per second"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      - alert: LowSuccessRate
        expr: rate(test_executions_total{status="success"}[10m]) / rate(test_executions_total[10m]) < 0.8
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low test success rate"
          description: "Test success rate is {{ $value | humanizePercentage }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% for more than 5 minutes"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 10 minutes"

  # ===================
  # CI/CD ALERTS
  # ===================
  - name: cicd_alerts
    rules:
      # Pipeline Failure Alerts
      - alert: CIPipelineFailure
        expr: cicd_pipeline_status{status="failed"} > 0
        for: 0m  # Immediate alert
        labels:
          severity: critical
          category: pipeline
        annotations:
          summary: "CI/CD Pipeline Failed"
          description: "Pipeline {{ $labels.pipeline_name }} failed on branch {{ $labels.branch }}"
          runbook_url: "https://docs.company.com/runbooks/ci-pipeline-failure"

      - alert: DeploymentFailure
        expr: cicd_deployment_status{status="failed"} > 0
        for: 0m  # Immediate alert
        labels:
          severity: critical
          category: deployment
        annotations:
          summary: "Deployment Failed"
          description: "Deployment of {{ $labels.service_name }} to {{ $labels.environment }} failed"
          runbook_url: "https://docs.company.com/runbooks/deployment-failure"

      # Performance Degradation Alerts
      - alert: SlowBuildPerformance
        expr: cicd_build_duration_seconds > 1800  # 30 minutes
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Build Performance Degraded"
          description: "Build time for {{ $labels.job_name }} is {{ $value }}s, exceeding 30 minute threshold"

      - alert: HighTestExecutionTime
        expr: cicd_test_duration_seconds > 600  # 10 minutes
        for: 2m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Test Execution Time High"
          description: "Test execution time for {{ $labels.test_suite }} is {{ $value }}s"

      # Test Quality Alerts
      - alert: TestSuiteFailureRate
        expr: (cicd_test_failures_total / cicd_test_executions_total) > 0.1
        for: 5m
        labels:
          severity: warning
          category: quality
        annotations:
          summary: "High Test Failure Rate"
          description: "Test failure rate is {{ $value | humanizePercentage }} for {{ $labels.test_suite }}"

      - alert: CoverageDropped
        expr: cicd_test_coverage_percentage < 80
        for: 10m
        labels:
          severity: warning
          category: quality
        annotations:
          summary: "Test Coverage Dropped"
          description: "Test coverage dropped to {{ $value }}% for {{ $labels.service_name }}"

      # Security Alerts
      - alert: SecurityVulnerabilitiesFound
        expr: cicd_security_vulnerabilities_total{severity="critical"} > 0
        for: 0m  # Immediate alert
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Critical Security Vulnerabilities Found"
          description: "{{ $value }} critical vulnerabilities found in {{ $labels.service_name }}"

      - alert: SecurityScanFailure
        expr: cicd_security_scan_status{status="failed"} > 0
        for: 1m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Security Scan Failed"
          description: "Security scan failed for {{ $labels.service_name }}"

      # Infrastructure Alerts
      - alert: DockerRegistryUnreachable
        expr: cicd_docker_registry_up == 0
        for: 2m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Docker Registry Unreachable"
          description: "Docker registry {{ $labels.registry_url }} is unreachable"

      - alert: ArtifactStorageFull
        expr: cicd_artifact_storage_usage_percentage > 90
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "Artifact Storage Nearly Full"
          description: "Artifact storage is {{ $value }}% full"

      # Pipeline Health Monitoring
      - alert: PipelineStalled
        expr: time() - cicd_pipeline_last_run_timestamp > 86400  # 24 hours
        for: 1h
        labels:
          severity: warning
          category: health
        annotations:
          summary: "Pipeline Has Not Run Recently"
          description: "Pipeline {{ $labels.pipeline_name }} has not run for over 24 hours"

      - alert: HighPipelineQueueLength
        expr: cicd_pipeline_queue_length > 10
        for: 15m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Pipeline Queue Backed Up"
          description: "{{ $value }} pipelines are queued, indicating potential bottleneck"

      # Deployment Monitoring
      - alert: DeploymentRollbackTriggered
        expr: increase(cicd_deployment_rollbacks_total[1h]) > 0
        for: 0m  # Immediate alert
        labels:
          severity: warning
          category: deployment
        annotations:
          summary: "Deployment Rollback Triggered"
          description: "Rollback triggered for {{ $labels.service_name }} in {{ $labels.environment }}"

      - alert: DeploymentFrequencyLow
        expr: rate(cicd_deployment_success_total[7d]) < 0.02  # Less than 1 deployment per day
        for: 1d
        labels:
          severity: info
          category: metrics
        annotations:
          summary: "Low Deployment Frequency"
          description: "Deployment frequency for {{ $labels.service_name }} is below expected rate"

      # Resource Usage Alerts
      - alert: CIRunnerHighCPU
        expr: cicd_runner_cpu_usage_percentage > 90
        for: 10m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "CI Runner High CPU Usage"
          description: "CI runner {{ $labels.runner_name }} CPU usage is {{ $value }}%"

      - alert: CIRunnerHighMemory
        expr: cicd_runner_memory_usage_percentage > 90
        for: 10m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "CI Runner High Memory Usage"
          description: "CI runner {{ $labels.runner_name }} memory usage is {{ $value }}%"

      # Integration and Dependencies
      - alert: ExternalServiceDown
        expr: cicd_external_service_up{service_type=~"github|dockerhub|npm"} == 0
        for: 5m
        labels:
          severity: critical
          category: dependencies
        annotations:
          summary: "External CI/CD Service Down"
          description: "External service {{ $labels.service_name }} is down, affecting CI/CD operations"

      # Compliance and Audit
      - alert: ComplianceCheckFailure
        expr: cicd_compliance_check_status{status="failed"} > 0
        for: 0m  # Immediate alert
        labels:
          severity: critical
          category: compliance
        annotations:
          summary: "Compliance Check Failed"
          description: "Compliance check failed for {{ $labels.check_type }} in {{ $labels.service_name }}"
