name: Emergency Validation
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'frontend/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  emergency-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "Backend exists: $([ -d backend ] && echo 'YES' || echo 'NO')"
        echo "Frontend exists: $([ -d frontend ] && echo 'YES' || echo 'NO')"
        echo "Package.json exists: $([ -f package.json ] && echo 'YES' || echo 'NO')"
    
    - name: Install root dependencies
      run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps
    
    - name: Install backend dependencies
      run: |
        if [ -d "backend" ]; then
          cd backend
          echo "Installing backend dependencies..."
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          echo "Backend dependencies installed successfully"
        else
          echo "Backend directory not found"
          exit 1
        fi
    
    - name: Install frontend dependencies
      run: |
        if [ -d "frontend" ]; then
          cd frontend
          echo "Installing frontend dependencies..."
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          echo "Frontend dependencies installed successfully"
        else
          echo "Frontend directory not found"
        fi
    
    - name: TypeScript check - Backend
      run: |
        cd backend
        echo "Running backend TypeScript check..."
        npm run typecheck
        echo "Backend TypeScript check passed"
    
    - name: TypeScript check - Frontend
      run: |
        if [ -d "frontend" ]; then
          cd frontend
          echo "Running frontend TypeScript check..."
          npm run type-check
          echo "Frontend TypeScript check passed"
        fi
    
    - name: Run backend tests
      run: |
        cd backend
        echo "Running backend tests..."
        npm test
        echo "Backend tests passed"
    
    - name: Run frontend tests
      run: |
        if [ -d "frontend" ]; then
          cd frontend
          echo "Running frontend tests..."
          npm test
          echo "Frontend tests passed"
        fi
    
    - name: Build backend
      run: |
        cd backend
        echo "Building backend..."
        npm run build
        echo "Backend build successful"
    
    - name: Build frontend
      run: |
        if [ -d "frontend" ]; then
          cd frontend
          echo "Building frontend..."
          npm run build
          echo "Frontend build successful"
        fi
    
    - name: Validate workflow success
      run: |
        echo "🎉 EMERGENCY VALIDATION SUCCESSFUL!"
        echo "All checks passed - workflow is now working at 100%"